/* eslint-disable prettier/prettier */

enum Type {
  CHART,
  OPTION,
}

enum Press {
  EMAIL,
  PLUS,
}

const dataTest = [
  {
    title: 'Chart',
    type: Type.CHART,
    data: [
      {
        id: 1,
        icon: 'icon-test',
        name: 'Chart 1',
      },
      {
        id: 2,
        icon: 'icon-test',
        name: 'Chart 2',
      },
      {
        id: 3,
        icon: 'icon-test',
        name: 'Chart 3',
      },
      {
        id: 4,
        icon: 'icon-test',
        name: 'Chart 4',
      },
    ],
  },
  {
    title: 'Options',
    type: Type.OPTION,
    data: [
      {
        id: 1,
        isNews: false,
        icon: 'icon-test',
        name: 'Liên kết ngay với ví điện tử',
      },
      {
        id: 2,
        isNews: true,
        icon: 'icon-test',
        name: 'Voucher giảm 50% cho đơn giá trên 30K',
      },
      {
        id: 3,
        isNews: true,
        icon: 'icon-test',
        name: 'Ưu đãi voucher giảm 20% cho đơn giá trên 30K',
      },
      {
        id: 4,
        isNews: false,
        icon: 'icon-test',
        name: 'Giới thiệu với bạn bè để nhận các ưu đãi',
      },
    ],
  },
];

const dataOrder = [
  {
    id: 1,
    title: 'Máy tính',
    nameShipper: 'Khánh Macro',
    engine: '29V1-55822',
    time: '5 phút',
    state: 'Đang xử lý',
  },
  {
    id: 2,
    title: 'Quần áo',
    nameShipper: 'Jack Lục Quân',
    engine: '26S1-12423',
    time: '30 phút',
    state: 'Đang giao',
  },
  {
    id: 3,
    title: 'Hoa hồng',
    nameShipper: 'Dũng Hà Đông',
    engine: '29T1-56788',
    time: '09/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 4,
    title: 'Rau',
    nameShipper: 'Của Nợ',
    engine: '29B-31243',
    time: '15 phút',
    state: 'Đang xử lý',
  },
  {
    id: 5,
    title: 'Trà sữa',
    nameShipper: 'Khánh Sky',
    engine: '88A1-56429',
    time: '11/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 6,
    title: 'Cơm rang',
    nameShipper: 'Hải Bánh',
    engine: '24U1-96953',
    time: '10/02/2022',
    state: 'Hủy',
  },
  {
    id: 7,
    title: 'Người yêu',
    nameShipper: 'Huấn Hoa Hồng',
    engine: '98Y1-34943',
    time: '14/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 8,
    title: 'Gì cũng được',
    nameShipper: 'Ngô Bá Khá',
    engine: '16E1-69584',
    time: '10 phút',
    state: 'Đang giao',
  },
  {
    id: 9,
    title: 'Máy tính',
    nameShipper: 'Khánh Macro',
    engine: '29V1-55822',
    time: '5 phút',
    state: 'Đang xử lý',
  },
  {
    id: 10,
    title: 'Quần áo',
    nameShipper: 'Jack Lục Quân',
    engine: '26S1-12423',
    time: '30 phút',
    state: 'Đang giao',
  },
  {
    id: 11,
    title: 'Hoa hồng',
    nameShipper: 'Dũng Hà Đông',
    engine: '29T1-56788',
    time: '09/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 12,
    title: 'Rau',
    nameShipper: 'Của Nợ',
    engine: '29B-31243',
    time: '15 phút',
    state: 'Đang xử lý',
  },
  {
    id: 13,
    title: 'Trà sữa',
    nameShipper: 'Khánh Sky',
    engine: '88A1-56429',
    time: '11/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 14,
    title: 'Cơm rang',
    nameShipper: 'Hải Bánh',
    engine: '24U1-96953',
    time: '10/02/2022',
    state: 'Hủy',
  },
  {
    id: 15,
    title: 'Người yêu',
    nameShipper: 'Huấn Hoa Hồng',
    engine: '98Y1-34943',
    time: '14/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 16,
    title: 'Gì cũng được',
    nameShipper: 'Ngô Bá Khá',
    engine: '16E1-69584',
    time: '10 phút',
    state: 'Đang giao',
  },
  {
    id: 17,
    title: 'Máy tính',
    nameShipper: 'Khánh Macro',
    engine: '29V1-55822',
    time: '5 phút',
    state: 'Đang xử lý',
  },
  {
    id: 18,
    title: 'Quần áo',
    nameShipper: 'Jack Lục Quân',
    engine: '26S1-12423',
    time: '30 phút',
    state: 'Đang giao',
  },
  {
    id: 19,
    title: 'Hoa hồng',
    nameShipper: 'Dũng Hà Đông',
    engine: '29T1-56788',
    time: '09/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 20,
    title: 'Rau',
    nameShipper: 'Của Nợ',
    engine: '29B-31243',
    time: '15 phút',
    state: 'Đang xử lý',
  },
  {
    id: 21,
    title: 'Trà sữa',
    nameShipper: 'Khánh Sky',
    engine: '88A1-56429',
    time: '11/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 22,
    title: 'Cơm rang',
    nameShipper: 'Hải Bánh',
    engine: '24U1-96953',
    time: '10/02/2022',
    state: 'Hủy',
  },
  {
    id: 23,
    title: 'Người yêu',
    nameShipper: 'Huấn Hoa Hồng',
    engine: '98Y1-34943',
    time: '14/02/2022',
    state: 'Hoàn thành',
  },
  {
    id: 24,
    title: 'Gì cũng được',
    nameShipper: 'Ngô Bá Khá',
    engine: '16E1-69584',
    time: '10 phút',
    state: 'Đang giao',
  },
];

export {dataTest, dataOrder, Type, Press};
